// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2ayruNEv-D1ArwV_KuSz2q78tkehvCnc',
    appId: '1:667641693045:web:32fe5275ea0fcd376e493c',
    messagingSenderId: '667641693045',
    projectId: 'reminder-11cc3',
    authDomain: 'reminder-11cc3.firebaseapp.com',
    storageBucket: 'reminder-11cc3.firebasestorage.app',
    measurementId: 'G-LFVD7P90R0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoO9klKL_JB3AhbZlavF3LNwFuLvRHEds',
    appId: '1:667641693045:android:6476fb5b00dada1c6e493c',
    messagingSenderId: '667641693045',
    projectId: 'reminder-11cc3',
    storageBucket: 'reminder-11cc3.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCm2HRHen2-Gg79LlFUt6fPkxN88nimi2c',
    appId: '1:667641693045:ios:58ae87bde502b44e6e493c',
    messagingSenderId: '667641693045',
    projectId: 'reminder-11cc3',
    storageBucket: 'reminder-11cc3.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCm2HRHen2-Gg79LlFUt6fPkxN88nimi2c',
    appId: '1:667641693045:ios:58ae87bde502b44e6e493c',
    messagingSenderId: '667641693045',
    projectId: 'reminder-11cc3',
    storageBucket: 'reminder-11cc3.firebasestorage.app',
    iosBundleId: 'com.example.reminder',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2ayruNEv-D1ArwV_KuSz2q78tkehvCnc',
    appId: '1:667641693045:web:8bc9a5aa89c3ffef6e493c',
    messagingSenderId: '667641693045',
    projectId: 'reminder-11cc3',
    authDomain: 'reminder-11cc3.firebaseapp.com',
    storageBucket: 'reminder-11cc3.firebasestorage.app',
    measurementId: 'G-FTKR0063F1',
  );
}
